# Generated by Django 4.2.1 on 2023-11-03 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientID', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=222)),
                ('adres', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outletsID', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('area', models.FloatField()),
                ('priceDay', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentID', models.IntegerField()),
                ('rentalPeriod', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.client')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.outlet')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentID', models.IntegerField()),
                ('sumPayment', models.FloatField()),
                ('datePayment', models.DateField()),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.rent')),
            ],
        ),
    ]
